name: Docker

on:
  workflow_call:

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Docker Build
      uses: docker/setup-buildx-action@v3.8.0

    - name: Download a Build Artifact
      uses: actions/download-artifact@v4.1.8
      with:
        name: programa

    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        username: ricutelo
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v6.11.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ricutelo/go_ci:${{gitgub.ref_name}}
               
